site_name: TaiBlockChain
nav:
  - TaiBlockChain :
      - TaiPublicChain :
          - TaiPublicChainEN :
              - Developer Platform :
                  - Install and build : Building-taiyuechain.md
                  - Interface Documentation : InterfaceDocumentation.md
                  - Usage : Usage.md
          - TaiPublicChainZN :  TaiYueChain.md
      - TaiUnionChain :
          - TaiUnionChainEN :  Building-taiyuechain.md
          - TaiUnionChainZN :  Building-taiyuechain.md
theme: readthedocs
repo_url: https://github.com/example/repository/

